{% set name = "kubessh" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kubessh-{{ version }}.tar.gz
  sha256: 7ccf719a0ce6abb2efb051b8f583a521c2c65cecbf6708c6008cbcbbdacf7ee8

build:
  number: 1
  noarch: python
  entry_points:
    - kubessh=kubessh.app:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - asyncssh
    - escapism
    - python-kubernetes
    - ptyprocess
    - ruamel.yaml
    - simpervisor
    - traitlets

test:
  imports:
    - kubessh
  commands:
    - pip check
    # The CLI call workd but it needs a cluster set. It "fails" with:
    # kubernetes.config.config_exception.ConfigException: Service host/port is not set.
    # I'll ask upstream if that is by design and then we can do something better to test the CLI.
    # - kubessh --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yuvipanda/kubessh
  summary: SSH server to spawn users into kubernetes pods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
