{% set name = "kubessh" %}
{% set version = "0.2.dev" %}
{% set commit = "f68801a5dabe7f9569f80b87807324c2c9c9223b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubessh/kubessh/archive/{{ commit }}.tar.gz
  sha256: bbc4d026e9081023ccdcf81725f71ec4576c4180cfb54cdd6d11fbe0b40a56a3

build:
  number: 0
  noarch: python
  entry_points:
    - kubessh=kubessh.app:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - aiohttp
    - asyncssh
    - escapism
    - python-kubernetes
    - ptyprocess
    - ruamel.yaml
    - simpervisor
    - traitlets

test:
  imports:
    - kubessh
  commands:
    - pip check
    # The CLI call workd but it needs a cluster set. It "fails" with:
    # kubernetes.config.config_exception.ConfigException: Service host/port is not set.
    # I'll ask upstream if that is by design and then we can do something better to test the CLI.
    # - kubessh --help
  requires:
    - pip

about:
  home: https://github.com/yuvipanda/kubessh
  summary: SSH server to spawn users into kubernetes pods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
